knp_paginator:
    page_range: 5              # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page        # Nom du paramètre GET pour la page
        sort_field_name: sort  # Tri
        sort_direction_name: direction
        distinct: true
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig' # Thème Bootstrap