knp_snappy:
    pdf:
        enabled: true
        binary: "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:
            enable-local-file-access: true
            load-error-handling: ignore
            load-media-error-handling: ignore
    image:
        enabled: true
        binary: "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:
            enable-local-file-access: true
            load-error-handling: ignore
            load-media-error-handling: ignore
