security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthentificatorAuthentificator
            entry_point: App\Security\LoginFormAuthentificatorAuthentificator
            form_login:
                login_path: app_auth
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            logout:
                path: app_logout
                target: app_auth
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/admin, roles: ResponsableRH }
        - { path: ^/profile, roles: Candidat }
