security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthentificatorAuthentificator
            entry_point: App\Security\LoginFormAuthentificatorAuthentificator
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login
                csrf_token_generator: security.csrf.token_manager
                csrf_token_id: logout
                invalidate_session: true
            remember_me:
                secret: "%kernel.secret%"
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/admin, roles: RH }
        - { path: ^/profile, roles: Candidat }
        - { path: ^/projet, roles: IS_AUTHENTICATED_FULLY}
        - { path: ^/projetFront, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/equipe, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/formation, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/reservation, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/employe, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/tache, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/participation, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/offre, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/candidature, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/offreFront, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/notification, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/evaluation, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/entretien, roles: IS_AUTHENTICATED_FULLY }
