controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: app_auth



# config/routes.yaml
chatbot:
    path: /chatbot
    controller: App\Controller\ChatbotController::handleChatbot
