# config/services.yaml

parameters:
    cvs_directory: '%kernel.project_dir%/public/uploads/cvs'
    lettres_directory: '%kernel.project_dir%/public/uploads/lettres'
    images_directory: '%kernel.project_dir%/public/uploads/images'
    qrcodes_directory: '%kernel.project_dir%/public/uploads/qrcodes'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration explicite pour les services spéciaux
    App\Twig\AppExtension:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags: ['twig.extension']

    App\Service\QRCodeService:
        arguments:
            $params: '@parameter_bag'

    App\Service\GoogleOAuthService:
        arguments:
            $params: '@parameter_bag'

    App\Service\GoogleMeetService:
        arguments:
            $googleOAuthService: '@App\Service\GoogleOAuthService'

    App\Service\TwilioService:
        arguments:
            $accountSid: '%env(twilio_account_sid)%'
            $authToken: '%env(twilio_auth_token)%'